/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tarea07_tatianagarcia;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author tatig
 */
public class MainMenu extends javax.swing.JFrame {
    private Color c;
    private Cabina cabin;
    private Armamentos armas;
    private Propulsores pro;
    private Alas alas2;
    private Nave nave;
    private ArrayList<Alas>ala = new ArrayList();
    private ArrayList <Propulsores> propulsor = new ArrayList();
    int peso3,peso2;

    /**
     * Creates new form Menu
     */
    public MainMenu() {
        initComponents();
        if(nave !=null){
            Agregar.setEnabled(false);
            AgregarNave.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChoqueFrame = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        indicedestruccion = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        AgregarNave = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        serie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Fecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        color = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cabina = new javax.swing.JButton();
        alas = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        propulsores1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        InfoNave = new javax.swing.JFrame();
        Tarea = new javax.swing.JFrame();
        jButton8 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        Cabina = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        numerodegente = new javax.swing.JTextField();
        pesocabina = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        Alas = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Peso2 = new javax.swing.JTextField();
        Longitud = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        Propulsores = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        Velocidad = new javax.swing.JTextField();
        Weight = new javax.swing.JTextField();
        Material = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Armamentos = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        power = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        Fondo = new javax.swing.JPanel();
        Choque = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        Listar = new javax.swing.JButton();
        BotonTarea = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        ChoqueFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("INDICE DE DESTRUCCION: ");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));
        jPanel6.add(indicedestruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 70, 30));

        jButton7.setBackground(new java.awt.Color(255, 51, 51));
        jButton7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(204, 204, 204));
        jButton7.setText("Regresar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 293, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/space-ship-crash.gif"))); // NOI18N
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 38, 427, 226));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star wars image.jpg"))); // NOI18N
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 350));

        ChoqueFrame.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 350));

        AgregarNave.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Serie:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 29, -1, 25));
        jPanel1.add(serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 28, 138, 25));

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 73, -1, 25));
        jPanel1.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 138, 25));

        jLabel4.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Cabina:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 119, -1, 25));

        color.setBackground(new java.awt.Color(0, 0, 204));
        color.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        color.setForeground(new java.awt.Color(204, 204, 204));
        color.setText("Añadir Info");
        color.setBorderPainted(false);
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });
        jPanel1.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Alas:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 162, -1, 25));

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("propulsores: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 205, -1, 25));

        jLabel7.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("NUMERO: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 248, -1, 25));

        jLabel8.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("COLOR: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 291, -1, 25));

        jLabel9.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("FECHA:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 334, -1, 25));

        cabina.setBackground(new java.awt.Color(0, 0, 204));
        cabina.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cabina.setForeground(new java.awt.Color(204, 204, 204));
        cabina.setText("Añadir Info");
        cabina.setBorderPainted(false);
        cabina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cabinaActionPerformed(evt);
            }
        });
        jPanel1.add(cabina, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 116, -1, -1));

        alas.setBackground(new java.awt.Color(0, 0, 204));
        alas.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        alas.setForeground(new java.awt.Color(204, 204, 204));
        alas.setText("Añadir Info");
        alas.setBorderPainted(false);
        alas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alasActionPerformed(evt);
            }
        });
        jPanel1.add(alas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 72, 138, 25));
        jPanel1.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 138, 25));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Agregar Info");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        propulsores1.setBackground(new java.awt.Color(0, 0, 204));
        propulsores1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        propulsores1.setForeground(new java.awt.Color(204, 204, 204));
        propulsores1.setText("Añadir Info");
        propulsores1.setBorderPainted(false);
        propulsores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propulsores1ActionPerformed(evt);
            }
        });
        jPanel1.add(propulsores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel24.setForeground(new java.awt.Color(51, 51, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star wars image.jpg"))); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        AgregarNave.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        javax.swing.GroupLayout InfoNaveLayout = new javax.swing.GroupLayout(InfoNave.getContentPane());
        InfoNave.getContentPane().setLayout(InfoNaveLayout);
        InfoNaveLayout.setHorizontalGroup(
            InfoNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        InfoNaveLayout.setVerticalGroup(
            InfoNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        Tarea.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setBackground(new java.awt.Color(204, 0, 51));
        jButton8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(204, 204, 204));
        jButton8.setText("Regresar");
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Tarea.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 100, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea7.png"))); // NOI18N
        Tarea.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 510));

        Cabina.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("PESO:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 43, 27));

        jLabel11.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("numero de tripulantes: ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 27));
        jPanel2.add(numerodegente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 110, 30));

        pesocabina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesocabinaActionPerformed(evt);
            }
        });
        jPanel2.add(pesocabina, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 80, 210, 30));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Agregar Info");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 130, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star wars image.jpg"))); // NOI18N
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        Cabina.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        Alas.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("PESO: ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 61, -1, -1));

        jLabel13.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("LONGITUD: ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 126, -1, -1));
        jPanel3.add(Peso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 55, 104, 29));
        jPanel3.add(Longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 120, 99, 29));

        jLabel14.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("ARMAMENTO:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 197, -1, -1));

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 204, 204));
        jButton4.setText("Añadir Info");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 191, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("Agregar Info");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 262, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star wars image.jpg"))); // NOI18N
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        Alas.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        Propulsores.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("PESO:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 62, -1, -1));

        jLabel16.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("MATERIAL:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 121, -1, -1));

        jLabel17.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("VELOCIDAD:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 176, -1, -1));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 204));
        jButton6.setText("Agregar Info");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 130, 30));
        jPanel4.add(Velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 111, 28));
        jPanel4.add(Weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 57, 111, 28));

        Material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaterialActionPerformed(evt);
            }
        });
        jPanel4.add(Material, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 111, 28));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star wars image.jpg"))); // NOI18N
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        Propulsores.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        Armamentos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("NOMBRE: ");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 58, -1, -1));

        jLabel19.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("peso:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 135, -1, -1));

        jLabel20.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("poder:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 205, -1, -1));
        jPanel5.add(power, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 134, 34));
        jPanel5.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 50, 134, 34));
        jPanel5.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 134, 34));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 204));
        jButton5.setText("Agregar Info");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 130, 30));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star wars image.jpg"))); // NOI18N
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        Armamentos.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(0, 0, 0));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Choque.setBackground(new java.awt.Color(102, 255, 102));
        Choque.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Choque.setForeground(new java.awt.Color(0, 0, 0));
        Choque.setText("Choque");
        Choque.setBorderPainted(false);
        Choque.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Choque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoqueActionPerformed(evt);
            }
        });
        Fondo.add(Choque, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, 30));

        Salir.setBackground(new java.awt.Color(204, 0, 0));
        Salir.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Fondo.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 361, -1, -1));

        Agregar.setBackground(new java.awt.Color(102, 255, 102));
        Agregar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Agregar.setForeground(new java.awt.Color(0, 0, 0));
        Agregar.setText("Nave");
        Agregar.setBorderPainted(false);
        Agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        Fondo.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 120, 30));

        Listar.setBackground(new java.awt.Color(102, 255, 102));
        Listar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Listar.setForeground(new java.awt.Color(0, 0, 0));
        Listar.setText("Info");
        Listar.setBorderPainted(false);
        Listar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });
        Fondo.add(Listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 100, 30));

        BotonTarea.setBackground(new java.awt.Color(102, 255, 102));
        BotonTarea.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        BotonTarea.setForeground(new java.awt.Color(0, 0, 0));
        BotonTarea.setText("Tarea");
        BotonTarea.setBorderPainted(false);
        BotonTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTareaActionPerformed(evt);
            }
        });
        Fondo.add(BotonTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star wars image.jpg"))); // NOI18N
        Fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        AgregarNave.setVisible(true);
        AgregarNave.pack();
        AgregarNave.setAlwaysOnTop(true);
        AgregarNave.setLocationRelativeTo(this);
        this.setVisible(false);
    }//GEN-LAST:event_AgregarActionPerformed

    private void cabinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cabinaActionPerformed
        Cabina.setVisible(true);
        Cabina.pack();
        Cabina.setAlwaysOnTop(true);
        Cabina.setLocationRelativeTo(this);
        AgregarNave.setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_cabinaActionPerformed

    private void MaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaterialActionPerformed

    private void pesocabinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesocabinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesocabinaActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int serie_nave = Integer.parseInt(serie.getText());
        String nombre = this.nombre.getText();
        int numero = Integer.parseInt(this.numero.getText());
        String cadena = Fecha.getText();
        String array[] = cadena.split("/");
        Date fecha = new Date(Integer.parseInt(array[2]), Integer.parseInt(array[1]), Integer.parseInt(array[0]));
        
        nave = new Nave(serie_nave, nombre, cabin, numero, c, fecha);
        nave.propulsor.add(pro);
        nave.ala.add(alas2);
        
        JOptionPane.showMessageDialog(null, "Cabina agregada");
        AgregarNave.setVisible(false);
        this.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        c = JColorChooser.showDialog(null, "Ingrese un color: ", Color.yellow);
    }//GEN-LAST:event_colorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int peso = Integer.parseInt(pesocabina.getText()); 
        int num_gente = Integer.parseInt(numerodegente.getText());
        
        cabin = new Cabina(peso, num_gente);
        Cabina.setVisible(false);
        AgregarNave.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void alasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alasActionPerformed
        Alas.setVisible(true);
        Alas.pack();
        Alas.setAlwaysOnTop(true);
        Alas.setLocationRelativeTo(this);
        AgregarNave.setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_alasActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        JOptionPane.showMessageDialog(null, ""+nave);
    }//GEN-LAST:event_ListarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        peso2 = Integer.parseInt(Peso2.getText()); 
        int longitud = Integer.parseInt(Longitud.getText());
        alas2 = new Alas(peso2, longitud, armas);
        
        
        Alas.setVisible(false);
        AgregarNave.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Armamentos.setVisible(true);
        Armamentos.pack();
        Armamentos.setAlwaysOnTop(true);
        Armamentos.setLocationRelativeTo(this);
        this.setVisible(false);
        Alas.setVisible(false);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        peso3 = Integer.parseInt(weight.getText()); 
        String nombre2 = name.getText(); 
        int poder = Integer.parseInt(power.getText());
        
        armas = new Armamentos(nombre2, peso3, poder);
        Armamentos.setVisible(false);
        Alas.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void propulsores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propulsores1ActionPerformed
        Propulsores.setVisible(true);
        Propulsores.pack();
        Propulsores.setAlwaysOnTop(true);
        Propulsores.setLocationRelativeTo(this);
        this.setVisible(false);
        AgregarNave.setVisible(false);
    }//GEN-LAST:event_propulsores1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int Peso1=Integer.parseInt(Weight.getText()); 
        String material=Material.getText();
        int velocidad=Integer.parseInt(Velocidad.getText());
        pro = new Propulsores(Peso1, material, velocidad);
        
        Propulsores.setVisible(false);
        AgregarNave.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ChoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoqueActionPerformed
        ChoqueFrame.setVisible(true);
        ChoqueFrame.pack();
        ChoqueFrame.setAlwaysOnTop(true);
        ChoqueFrame.setLocationRelativeTo(this);
        int tot= nave.getC().getPeso()+peso3+peso2;
        indicedestruccion.setText(String.valueOf(tot));
        
        this.setVisible(false);
        AgregarNave.setVisible(false);
    }//GEN-LAST:event_ChoqueActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ChoqueFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void BotonTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTareaActionPerformed
        Tarea.setVisible(true);
        Tarea.pack();
        Tarea.setAlwaysOnTop(true);
        Tarea.setLocationRelativeTo(this);
        this.setVisible(false);
    }//GEN-LAST:event_BotonTareaActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Tarea.setVisible(false);
        this.pack();
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(this);
        this.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JFrame AgregarNave;
    private javax.swing.JFrame Alas;
    private javax.swing.JFrame Armamentos;
    private javax.swing.JButton BotonTarea;
    private javax.swing.JFrame Cabina;
    private javax.swing.JButton Choque;
    private javax.swing.JFrame ChoqueFrame;
    private javax.swing.JTextField Fecha;
    private javax.swing.JPanel Fondo;
    private javax.swing.JFrame InfoNave;
    private javax.swing.JButton Listar;
    private javax.swing.JTextField Longitud;
    private javax.swing.JTextField Material;
    private javax.swing.JTextField Peso2;
    private javax.swing.JFrame Propulsores;
    private javax.swing.JButton Salir;
    private javax.swing.JFrame Tarea;
    private javax.swing.JTextField Velocidad;
    private javax.swing.JTextField Weight;
    private javax.swing.JButton alas;
    private javax.swing.JButton cabina;
    private javax.swing.JButton color;
    private javax.swing.JTextField indicedestruccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField numerodegente;
    private javax.swing.JTextField pesocabina;
    private javax.swing.JTextField power;
    private javax.swing.JButton propulsores1;
    private javax.swing.JTextField serie;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
